from src.Concepts.Role import Role
from src.Concepts.Rolegroup import Rolegroup as RG

class Gamemodus:
    """ All possible Gamemodi which can be played in Town of Salem. """
    CLASSIC = [{Role.SHERIFF}, {Role.DOCTOR}, {Role.INVESTIGATOR}, {Role.JAILOR}, {Role.MEDIUM}, {Role.GODFATHER},
        {Role.FRAMER}, {Role.EXECUTIONER}, {Role.ESCORT}, {Role.MAFIOSO}, {Role.LOOKOUT}, {Role.SERIALKILLER},
        RG.NC_TOWN_KILLING, {Role.JESTER}, RG.NC_TOWN]

    OLD_RANKED_PRACTICE = [{Role.JAILOR}, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_SUPPORT,
        RG.NC_TOWN_SUPPORT, RG.NC_TOWN_PROTECTIVE, RG.NC_TOWN_KILLING, RG.NC_TOWN, {Role.GODFATHER}, {Role.MAFIOSO},
        RG.NC_MAFIA, RG.NC_NEUTRAL_KILLING, RG.NC_NEUTRAL_EVIL, RG.NC_NEUTRAL_BENIGN, RG.NC_ALL]

    NEW_RANKED_PRACTICE = [{Role.JAILOR}, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_PROTECTIVE,
        RG.NC_TOWN_KILLING, RG.NC_TOWN_SUPPORT, RG.NC_TOWN, RG.NC_TOWN, RG.NC_TOWN, {Role.GODFATHER}, {Role.MAFIOSO},
        RG.NC_MAFIA, RG.NC_MAFIA, RG.NC_NEUTRAL_EVIL, RG.NC_NEUTRAL_KILLING]

    RANKED = [{Role.JAILOR}, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_INVESTIGATIVE, RG.NC_TOWN_PROTECTIVE, RG.NC_TOWN_KILLING,
        RG.NC_TOWN_SUPPORT, RG.NC_TOWN, RG.NC_TOWN, RG.NC_TOWN, {Role.GODFATHER}, {Role.MAFIOSO}, RG.NC_MAFIA, RG.NC_MAFIA,
        RG.NC_NEUTRAL_EVIL, RG.NC_NEUTRAL_KILLING]